[project]
name = "2026-5-9-python-class"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib==3.11.0",
    "numpy==2.5.0",
    "opencv-python==4.13.0.92",
    "pandas==3.0.3",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
    "reportlab==5.0.0",
    "requests==2.34.2",
    "scikit-image==0.26.0",
    "streamlit>=1.58.0",
    "yfinance>=1.5.1",
]
